"""add_versioning_and_soft_delete_to_candidates

Revision ID: 0375ed483df0
Revises: a890dbce7895
Create Date: 2026-06-15 23:21:48.270829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0375ed483df0'
down_revision: Union[str, Sequence[str], None] = 'a890dbce7895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('candidates', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('candidates', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('candidates', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'candidates', 'candidates', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'deleted_at')
    op.drop_column('candidates', 'parent_id')
    op.drop_column('candidates', 'is_active')
    op.drop_column('candidates', 'version')
    # ### end Alembic commands ###
