"""add_job_fields

Revision ID: 356fceb7530a
Revises: 69b3a8731ba4
Create Date: 2026-06-16 22:09:12.739577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356fceb7530a'
down_revision: Union[str, Sequence[str], None] = '69b3a8731ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_email_active_unique'), table_name='candidates', postgresql_where='((is_active = true) AND (deleted_at IS NULL))')
    op.add_column('job_positions', sa.Column('location', sa.String(), nullable=True))
    op.add_column('job_positions', sa.Column('employment_type', sa.String(), nullable=True))
    op.add_column('job_positions', sa.Column('work_model', sa.String(), nullable=True))
    op.add_column('job_positions', sa.Column('responsibilities', sa.Text(), nullable=True))
    op.add_column('job_positions', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('job_positions', sa.Column('benefits', sa.Text(), nullable=True))
    op.add_column('job_positions', sa.Column('application_email', sa.String(), nullable=True))
    op.add_column('job_positions', sa.Column('application_subject', sa.String(), nullable=True))
    op.add_column('job_positions', sa.Column('deadline', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_positions', 'deadline')
    op.drop_column('job_positions', 'application_subject')
    op.drop_column('job_positions', 'application_email')
    op.drop_column('job_positions', 'benefits')
    op.drop_column('job_positions', 'requirements')
    op.drop_column('job_positions', 'responsibilities')
    op.drop_column('job_positions', 'work_model')
    op.drop_column('job_positions', 'employment_type')
    op.drop_column('job_positions', 'location')
    op.create_index(op.f('ix_candidates_email_active_unique'), 'candidates', ['email'], unique=True, postgresql_where='((is_active = true) AND (deleted_at IS NULL))')
    # ### end Alembic commands ###
