"""add_slug_to_job_positions

Revision ID: 39cf2631e1c8
Revises: fd028f3c38e3
Create Date: 2026-06-24 04:11:08.861236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39cf2631e1c8'
down_revision: Union[str, Sequence[str], None] = 'fd028f3c38e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_positions', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_job_positions_slug'), 'job_positions', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_positions_slug'), table_name='job_positions')
    op.drop_column('job_positions', 'slug')
    # ### end Alembic commands ###
