"""add_blacklist_fields_to_candidates

Revision ID: 69b3a8731ba4
Revises: c5425e3f18a7
Create Date: 2026-06-16 01:26:26.363769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b3a8731ba4'
down_revision: Union[str, Sequence[str], None] = 'c5425e3f18a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('is_flagged', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('candidates', sa.Column('flagged_reason', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'flagged_at')
    op.drop_column('candidates', 'flagged_reason')
    op.drop_column('candidates', 'is_flagged')
    # ### end Alembic commands ###
