"""add_job_applications_table

Revision ID: 921235d54e22
Revises: 39cf2631e1c8
Create Date: 2026-06-24 04:20:41.357490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921235d54e22'
down_revision: Union[str, Sequence[str], None] = '39cf2631e1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('job_position_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('form_full_name', sa.String(), nullable=True),
    sa.Column('form_email', sa.String(), nullable=True),
    sa.Column('form_phone', sa.String(), nullable=True),
    sa.Column('form_address', sa.String(), nullable=True),
    sa.Column('form_linkedin', sa.String(), nullable=True),
    sa.Column('form_cover_letter', sa.Text(), nullable=True),
    sa.Column('original_pdf_url', sa.String(), nullable=True),
    sa.Column('pdf_hash', sa.String(), nullable=True),
    sa.Column('ai_extracted_data', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_alerts', sa.JSON(), nullable=True),
    sa.Column('has_divergence', sa.Boolean(), nullable=True),
    sa.Column('divergence_report', sa.JSON(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_position_id', 'tenant_id', name='uq_application_candidate_job_tenant')
    )
    op.create_index(op.f('ix_job_applications_pdf_hash'), 'job_applications', ['pdf_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_applications_pdf_hash'), table_name='job_applications')
    op.drop_table('job_applications')
    # ### end Alembic commands ###
