"""add_quality_score_to_candidates

Revision ID: a890dbce7895
Revises: 1bd8a5184eea
Create Date: 2026-06-15 18:04:23.698553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a890dbce7895'
down_revision: Union[str, Sequence[str], None] = '1bd8a5184eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('candidates', sa.Column('quality_alerts', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'quality_alerts')
    op.drop_column('candidates', 'quality_score')
    # ### end Alembic commands ###
