"""add_pdf_hash_and_partial_email_unique_index

Revision ID: c5425e3f18a7
Revises: 0375ed483df0
Create Date: 2026-06-15 23:56:30.251845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5425e3f18a7'
down_revision: Union[str, Sequence[str], None] = '0375ed483df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('pdf_hash', sa.String(), nullable=True))
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_index(op.f('ix_candidates_pdf_hash'), 'candidates', ['pdf_hash'], unique=False)
    op.create_index('ix_candidates_email_active_unique', 'candidates', ['email'], unique=True, postgresql_where=sa.text('is_active = true AND deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidates_email_active_unique', table_name='candidates')
    op.drop_index(op.f('ix_candidates_pdf_hash'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.drop_column('candidates', 'pdf_hash')
    # ### end Alembic commands ###
