"""make_category_and_skill_tenant_scoped_unique

Revision ID: f54b27ab7a01
Revises: f7fafd77c98b
Create Date: 2026-06-21 13:56:56.297617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54b27ab7a01'
down_revision: Union[str, Sequence[str], None] = 'f7fafd77c98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_unique_constraint('uq_category_tenant_name', 'categories', ['tenant_id', 'name'])
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=False)
    op.create_unique_constraint('uq_skill_tenant_name', 'skills', ['tenant_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_skill_tenant_name', 'skills', type_='unique')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.drop_constraint('uq_category_tenant_name', 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    # ### end Alembic commands ###
