"""add_stripe_billing_to_tenants

Revision ID: fd028f3c38e3
Revises: 9e2b62eb4039
Create Date: 2026-06-21 14:39:24.333777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd028f3c38e3'
down_revision: Union[str, Sequence[str], None] = '9e2b62eb4039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('plan_name', sa.String(), server_default='free', nullable=False))
    op.add_column('tenants', sa.Column('plan_status', sa.String(), server_default='active', nullable=False))
    op.add_column('tenants', sa.Column('candidate_count_limit', sa.Integer(), server_default='50', nullable=False))
    op.create_index(op.f('ix_tenants_stripe_customer_id'), 'tenants', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_tenants_stripe_subscription_id'), 'tenants', ['stripe_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_stripe_subscription_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_stripe_customer_id'), table_name='tenants')
    op.drop_column('tenants', 'candidate_count_limit')
    op.drop_column('tenants', 'plan_status')
    op.drop_column('tenants', 'plan_name')
    op.drop_column('tenants', 'stripe_subscription_id')
    op.drop_column('tenants', 'stripe_customer_id')
    # ### end Alembic commands ###
