'use client';

import { useState, type FormEvent } from 'react';
import { KeyRound } from 'lucide-react';
import { apiFetch } from '@/lib/api';
import StatusMessage from '@/components/StatusMessage';
import { Input } from '@/components/ui/input';

export default function SettingsSecurityPage() {
  const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [isSaving, setIsSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); setMessage(null); if (newPassword !== confirmation) { setError('A nova senha e a confirmação não coincidem.'); return; } if (newPassword.length < 8) { setError('A nova senha deve conter pelo menos 8 caracteres.'); return; } setIsSaving(true); try { await apiFetch('/api/auth/change-password', { method: 'POST', body: JSON.stringify({ current_password: currentPassword, new_password: newPassword }) }); setCurrentPassword(''); setNewPassword(''); setConfirmation(''); setMessage('Sua senha foi alterada com sucesso.'); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Não foi possível alterar sua senha.'); } finally { setIsSaving(false); } }
  return <main className="max-w-2xl"><section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="mb-6 flex gap-3"><KeyRound className="h-5 w-5 text-primary" aria-hidden="true" /><div><h1 className="font-semibold">Segurança da conta</h1><p className="mt-1 text-sm text-muted-foreground">Use uma senha exclusiva com, no mínimo, 8 caracteres.</p></div></div>{error && <StatusMessage tone="error" className="mb-5">{error}</StatusMessage>}{message && <StatusMessage tone="success" className="mb-5">{message}</StatusMessage>}<form onSubmit={submit} className="space-y-5"><label className="block text-sm font-medium" htmlFor="current-password">Senha atual<Input id="current-password" required type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} className="mt-1.5" /></label><label className="block text-sm font-medium" htmlFor="new-password">Nova senha<Input id="new-password" required minLength={8} type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} placeholder="Mínimo de 8 caracteres" className="mt-1.5" /></label><label className="block text-sm font-medium" htmlFor="confirm-password">Confirmar nova senha<Input id="confirm-password" required minLength={8} type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="mt-1.5" /></label><button type="submit" disabled={isSaving} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-60">{isSaving ? 'Salvando…' : 'Alterar senha'}</button></form></section></main>;
}
