'use client';

import { useEffect, useState, type FormEvent } from 'react';
import { Bell, Palette, SlidersHorizontal } from 'lucide-react';
import { useTheme } from 'next-themes';
import { apiFetch } from '@/lib/api';
import StatusMessage from '@/components/StatusMessage';
import { useUnsavedChanges } from '@/hooks/useUnsavedChanges';

type Preferences = { timezone: string; email_notifications: boolean; theme: 'system' | 'light' | 'dark' };

export default function SettingsPreferencesPage() {
  const { setTheme } = useTheme();
  const [preferences, setPreferences] = useState<Preferences | null>(null); const [timezone, setTimezone] = useState('America/Sao_Paulo'); const [emailNotifications, setEmailNotifications] = useState(true); const [theme, setSelectedTheme] = useState<Preferences['theme']>('system'); const [isSaving, setIsSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const hasUnsavedChanges = Boolean(preferences && (timezone !== preferences.timezone || emailNotifications !== preferences.email_notifications || theme !== preferences.theme));
  useUnsavedChanges(hasUnsavedChanges);
  useEffect(() => { void apiFetch<Preferences>('/api/auth/me').then((data) => { setPreferences(data); setTimezone(data.timezone); setEmailNotifications(data.email_notifications); setSelectedTheme(data.theme); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Não foi possível carregar suas preferências.')); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setIsSaving(true); setError(null); setMessage(null); try { const updated = await apiFetch<Preferences>('/api/auth/me', { method: 'PATCH', body: JSON.stringify({ timezone, email_notifications: emailNotifications, theme }) }); setPreferences(updated); setTheme(updated.theme); setMessage('Preferências atualizadas com sucesso.'); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Não foi possível salvar suas preferências.'); } finally { setIsSaving(false); } }
  return <main className="max-w-2xl"><section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="mb-6 flex gap-3"><SlidersHorizontal className="h-5 w-5 text-primary" aria-hidden="true" /><div><h1 className="font-semibold">Preferências</h1><p className="mt-1 text-sm text-muted-foreground">Escolha como o TalentFlow deve acompanhar seu trabalho.</p></div></div>{error && <StatusMessage tone="error" className="mb-5">{error}</StatusMessage>}{message && <StatusMessage tone="success" className="mb-5">{message}</StatusMessage>}<form onSubmit={submit} className="space-y-6"><label className="block text-sm font-medium" htmlFor="timezone">Fuso horário<select id="timezone" value={timezone} onChange={(event) => setTimezone(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-input bg-background px-3 text-sm"><option value="America/Sao_Paulo">Brasília (UTC−03:00)</option><option value="America/Manaus">Manaus (UTC−04:00)</option><option value="America/Rio_Branco">Rio Branco (UTC−05:00)</option></select></label><fieldset><legend className="flex items-center gap-2 text-sm font-medium"><Palette className="h-4 w-4 text-primary" />Tema</legend><div className="mt-3 grid gap-2 sm:grid-cols-3">{([{ value: 'system', label: 'Automático' }, { value: 'light', label: 'Claro' }, { value: 'dark', label: 'Escuro' }] as const).map((option) => <label key={option.value} className={`cursor-pointer rounded-xl border p-3 text-sm ${theme === option.value ? 'border-primary bg-primary/10 text-primary' : 'border-border hover:bg-accent'}`}><input type="radio" name="theme" value={option.value} checked={theme === option.value} onChange={() => setSelectedTheme(option.value)} className="sr-only" />{option.label}</label>)}</div></fieldset><label className="flex cursor-pointer items-start gap-3 rounded-xl border border-border p-4 text-sm"><input type="checkbox" checked={emailNotifications} onChange={(event) => setEmailNotifications(event.target.checked)} className="mt-0.5 h-4 w-4 rounded border-border text-primary" /><span><Bell className="mb-1 h-4 w-4 text-primary" aria-hidden="true" /><span className="block font-medium">Notificações operacionais por e-mail</span><span className="mt-1 block text-muted-foreground">Receba avisos importantes sobre o uso da sua conta.</span></span></label><button type="submit" disabled={isSaving || !preferences} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-60">{isSaving ? 'Salvando…' : 'Salvar preferências'}</button></form></section></main>;
}
